"""Initial migration

Revision ID: 95692b93cd00
Revises: 
Create Date: 2024-10-01 22:26:09.891996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95692b93cd00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_parcel_types_id'), 'parcel_types', ['id'], unique=False)
    op.create_table('transport_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_transport_companies_id'), 'transport_companies', ['id'], unique=False)
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('parcel_type_id', sa.Integer(), nullable=False),
    sa.Column('delivery_cost', sa.Float(), nullable=True),
    sa.Column('transport_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parcel_type_id'], ['parcel_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'transport_company_id', name='uix_parcel_company')
    )
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_transport_companies_id'), table_name='transport_companies')
    op.drop_table('transport_companies')
    op.drop_index(op.f('ix_parcel_types_id'), table_name='parcel_types')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
