"""insert_dicts

Revision ID: asuu22ge211l
Revises: cdee23bc868e
Create Date: 2024-10-02 21:25:08.729483

"""

from typing import Sequence, Union

import os
import json
import sqlalchemy as sa

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Boolean


# revision identifiers, used by Alembic.
revision: str = 'asuu22ge211l'
down_revision: Union[str, None] = 'cdee23bc868e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

file_path = 'alembic/cls/'
def get_files_in_directory(dir_path):
    return [f for f in os.listdir(dir_path) if os.path.isfile(os.path.join(dir_path, f))]

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    file_list = [file for file in get_files_in_directory(file_path)]
    for file in file_list:
        with open(file_path + file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        table_name = file[:-5]
        columns = [column('id', Integer), column('name', String)]
        current_table = table(table_name, *columns)
        op.bulk_insert(current_table, data)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    file_list = [file for file in get_files_in_directory(file_path)]
    for file in file_list:
        table_name = file[:-5]
        op.execute('DELETE FROM ' + table_name)
    # ### end Alembic commands ###