"""foreign_key_company

Revision ID: cdee23bc868e
Revises: 95692b93cd00
Create Date: 2024-10-02 17:59:08.729483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdee23bc868e'
down_revision: Union[str, None] = '95692b93cd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'parcels', 'transport_companies', ['transport_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    # ### end Alembic commands ###
