"""user_id

Revision ID: e6c347109f79
Revises: asuu22ge211l
Create Date: 2024-10-03 18:34:19.384244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c347109f79'
down_revision: Union[str, None] = 'asuu22ge211l'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('user_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcels', 'user_id')
    # ### end Alembic commands ###
